# Generated by Django 3.2.16 on 2022-10-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221013_0813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lang',
        ),
    ]
